### ISSUE TITLE
Granular and Extended Event Alerting

### ISSUE THREAD

**Issue by tylerauerbeck** [bitnami-labs/kubewatch#105]
There have been a few requests to be able to be very specific about what types of events kubewatch alerts on.

For example, rather than being alerted of all events when you subscribe to an object like `pods`, you may just be interested in a single action (`create`,`update`,`delete`). So we may want to have our yaml file look something like:

```
resource:
  deployment: true
    events:
      update: true
  replicationcontroller: false
  replicaset: false
  daemonset: false
  services: false
  pod: true
  job: false
  persistentvolume: false
  namespace: true
    events:
       delete: true
  node: false
```

There are also some types of objects that have a larger series of events, such as jobs. Specifically for the Job type, it may be interested to see whether the job completed successfully or if it failed.

This issue is to discuss

- How best to implement the subscription of specific events rather than all events of an object
- Is it a goal of Kubewatch to subscribe to these extended events or to just cover the normal create,update,delete events? If we are interested in the extended events, what's the best way to accomplish this?
