### ISSUE TITLE
Setting resourcesToWatch.pod to false causes kubewatch pod to crashbackoffloop

### ISSUE THREAD

**Issue by shahiddev** [bitnami-labs/kubewatch#124]
using stable/kubewatch v0.0.4 - stable (chart version 0.4.1)

I'm seeing this issue where if you set `resourcesToWatch.pod` to false the pod goes into a crashbackoffloop

For example the following values file works fine
```
rbac:
  create: true
resourcesToWatch:
  daemonset: false
  deployment: true
  pod: true
  replicaset: false
  replicationcontroller: false
  services: false
  secret: false
  configmap: false
slack:
  channel: "#k8s"
  token: "<token here>"
```
but changing just the pod line to false causes the pod to crash
