### ISSUE TITLE
No notification when when config-map changes

### ISSUE THREAD

**Issue by anoopwebs** [bitnami-labs/kubewatch#137]
It observed that a chnages in config-map doesn't create any notification, does that expected?
I see configmap as a supported resources in code but as per pod logs its not synced. I tried to get notifications for config map, secrets, name space and persistant volume. In logs I see all are synced except config map.

Kubernetes version: 1.9.9
kubewatch docker image: latest 

    time="2018-09-24T16:57:31Z" level=info msg="Kubewatch controller synced and ready" pkg=kubewatch-namespace
    time="2018-09-24T16:57:31Z" level=info msg="Kubewatch controller synced and ready" pkg="kubewatch-persistent volume"
    time="2018-09-24T16:57:31Z" level=info msg="Kubewatch controller synced and ready" pkg=kubewatch-secret```

**Comment by vaibhavkhurana2018** [comment]
I am also facing the same issue. Config-maps are not synced. 

```
INFO[0000] Kubewatch controller synced and ready         pkg=kubewatch-pod
INFO[0000] Kubewatch controller synced and ready         pkg=kubewatch-namespace
INFO[0000] Kubewatch controller synced and ready         pkg=kubewatch-service
```
The below is the config file: 

```
namespace: "default" 
resource:
  deployment: true
  replicationcontroller: false
  replicaset: false
  daemonset: true
  services: true
  pod: true
  secret: false
  configmap: true
  namespace : true
```

Let me know if i am doing something wrong.
