### ISSUE TITLE
Unable to pull the kubectl image due to the unauthorized error

### ISSUE THREAD

**Issue by kthallam** [bitnami-labs/kubewatch#143]
While creating the kubewatch pod on the cluster it is unable to pull and load the image of kubectl due to unauthorized error . 

So is there any alternate image that we can use for that. 

Thank you in advance.

**Comment by snebel29** [comment]
Hi @kthallam 
What image are you using? Can you be more explicit on how are you deploying kubewatch?

Doing a simple deployment seems to be just working fine for me
```
$ kubectl run kubewatch --image=bitnami/kubewatch
deployment "kubewatch" created
```

Cheers

**Comment by kthallam** [comment]
I am trying to create the pod on our kubernetes cluster by using the kubewatch.yaml which is present in the repository.

**Comment by snebel29** [comment]
@kthallam 
[That file](https://github.com/bitnami-labs/kubewatch/blob/5772afdd620a4b2bfe26f71e2dfb6d6a96b076cb/kubewatch.yaml) looks old and I doubt you really need it.

Why don't you just deploy it using a kubernetes depoyment as I've posted in my comment above? you could as well use the available helm chart, as explained [here](https://github.com/bitnami-labs/kubewatch#installing-kubewatch-using-helm)

Cheers

**Comment by grantholly** [comment]
The image: gcr.io/skippbox/kubectl:v1.3.0 seems to be the problem.

Looks like there are other images available for kubewatch (for example: https://hub.docker.com/r/bitnami/kubewatch/)

**Comment by tdmalone** [comment]
Ran into this issue as well.

It might be a good idea to update https://github.com/bitnami-labs/kubewatch/blob/master/kubewatch.yaml :)

**Comment by tdmalone** [comment]
This issue is similar to #135

**Comment by tdmalone** [comment]
Here's an updated `kubewatch.yaml` for others coming across this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: default
spec:
  serviceAccountName: kubewatch
  containers:
  - image: bitnami/kubewatch
    imagePullPolicy: Always
    name: kubewatch
    volumeMounts:
    - name: config-volume
      mountPath: /root
  restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch
```

This removes the (old?) proxy container and updates the main image name.
(I haven't got this to fully work yet with the [service account](https://github.com/bitnami-labs/kubewatch/blob/master/kubewatch-service-account.yaml), but perhaps that's out of date too?)
