### ISSUE TITLE
Ignore SSL certificate for hipchat

### ISSUE THREAD

**Issue by udaykiran19** [bitnami-labs/kubewatch#158]
We have self-signed certificate for hipchat server. Is there any flag i can set insecure = true  to ignore the error or any workaround to solve this problem ?

Logs-
time="2018-12-10T10:37:06Z" level=info msg="Processing update to pod: default/nginx-deployment-75675f5897-d6zrn" pkg=kubewatch-pod
time="2018-12-10T10:37:06Z" level=info msg="Processing update to deployment: default/nginx-deployment" pkg=kubewatch-deployment
2018/12/10 10:37:06 Post https://hipchat.internal/room/425/notification: x509: certificate signed by unknown authority
2018/12/10 10:37:06 Post https://hipchat.internal/room/425/notification: x509: certificate signed by unknown authority

**Comment by wannaknowmo** [comment]
any luck to go around https?

**Comment by udaykiran19** [comment]
use insecure_skip_verify: true under http_config.

See documentation.
https://prometheus.io/docs/alerting/configuration/#http_config

**Comment by udaykiran19** [comment]
Something like this

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
  namespace: kube-system  
  labels:
    app: kubewatch
data:
  .kubewatch.yaml: |
    handler:
      hipchat:
        token: "asdasdasdasd"
        room: "42"
        url: "https://hipchat.internal/v2/"
    resource:
      deployment: true
      pod: true
      services: true
      ingress: true
      daemonset: false
      job: false
      persistentvolume: false      
      replicaset: false
      replicationcontroller: false
```
