### ISSUE TITLE
Kubewatch for clusterrole and serviceaccount resource

### ISSUE THREAD

**Issue by prasenforu** [bitnami-labs/kubewatch#166]
Not sure its supported or not but I tried to add below two resource in config file but not working.
- clusterrole 
- serviceaccount 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
data:
  .kubewatch.yaml: |
    namespace: ""
    handler:
      webhook:
        url: "http://webhook_url"
    resource:
      deployment: true
      replicationcontroller: true
      replicaset: true
      daemonset: true
      services: true
      pod: true
      secret: true
      configmap: true
      job: true
      persistentvolume: true
      namespace: true
      ingress: true
      clusterrole: true
      serviceaccount: true
```

logs from pod

```
==> Config file exists...
time="2019-03-03T11:14:05Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-pod
time="2019-03-03T11:14:05Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-daemonset
time="2019-03-03T11:14:05Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-replicaset
time="2019-03-03T11:14:05Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-service
time="2019-03-03T11:14:05Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-deployment
time="2019-03-03T11:14:05Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-namespace
time="2019-03-03T11:14:05Z" level=info msg="Starting kubewatch controller" pkg="kubewatch-replication controller"
time="2019-03-03T11:14:05Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-job
time="2019-03-03T11:14:05Z" level=info msg="Starting kubewatch controller" pkg="kubewatch-persistent volume"
time="2019-03-03T11:14:05Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-secret
time="2019-03-03T11:14:05Z" level=info msg="Starting kubewatch controller" pkg=kubewatch-ingress
time="2019-03-03T11:14:05Z" level=info msg="Processing add to namespace: default" pkg=kubewatch-namespace
time="2019-03-03T11:14:05Z" level=info msg="Processing add to namespace: kube-system" pkg=kubewatch-namespace
time="2019-03-03T11:14:05Z" level=info msg="Processing add to namespace: kube-public" pkg=kubewatch-namespace
time="2019-03-03T11:14:05Z" level=info msg="Processing add to namespace: monitoring" pkg=kubewatch-namespace
ERROR: logging before flag.Parse: E0303 11:14:05.818617       1 reflector.go:205] github.com/bitnami-labs/kubewatch/pkg
```
