### ISSUE TITLE
webhook not working

### ISSUE THREAD

**Issue by MohitArora1** [bitnami-labs/kubewatch#192]
i added webhook URL, and have not configure slack channel and token, it still looking for slack channel and token not sending events on webhook.

**Comment by MohitArora1** [comment]
![Screenshot from 2019-09-09 12-59-01](https://user-images.githubusercontent.com/26607296/64511293-9f25e680-d301-11e9-99f5-167db38cc66a.png)

**Comment by Joshi425** [comment]
in the examples in the  readme there is the wrong container, 
this is probably what you want:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
  namespace: kube-system
data:
  .kubewatch.yaml: |
    namespace: ""
    handler:
      webhook:
        url: "YOUR_URL"
    resource:
      deployment: true
      replicationcontroller: false
      replicaset: false
      daemonset: true
      services: true
      pod: false
      secret: true
      configmap: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubewatch
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kubewatch
  template:
    metadata:
      labels:
        app: kubewatch
    spec:
      containers:
      - image: bitnami/kubewatch:0.0.4
        imagePullPolicy: Always
        name: kubewatch
        volumeMounts:
        - name: config-volume
          mountPath: /opt/bitnami/kubewatch/.kubewatch.yaml
          subPath: .kubewatch.yaml
      - image: quay.io/coreos/hyperkube:v1.10.3_coreos.0
        command: ["kubectl"]
        args:
        - proxy
        - "-p"
        - "8080"
        name: proxy
        imagePullPolicy: Always
      volumes:
      - name: config-volume
        configMap:
           name: kubewatch
```
