### ISSUE TITLE
setting slack token in secret

### ISSUE THREAD

**Issue by enviosystemsdevops** [bitnami-labs/kubewatch#197]
Hi, I wonder if I could set the slack token in a secret instead of setting it in the values-file.yml

**Comment by mkmik** [comment]
I agree, this seems quite important; not only slack tokens, but all sorts of secrets/passwords in hook configurations

**Comment by dudicoco** [comment]
You can do it with secrets populated into environment variables: https://github.com/bitnami-labs/kubewatch/blob/b9ee12c93edd6ff5a5f9d511a47539c9cca7d87c/README.md#slack

**Comment by mkmik** [comment]
the kubewatch config command is confusing; all it does is to write/modify a yaml config file.

The command itself indeed does accept the secrets from environment variables, but then it writes the content of those environment variables into the file.

What @enviosystemsdevops asked is to put the secrets in a k8s `apiVersion: v1`, `kind: Secret` resource, which would be right thing to do.

Due to historical reasons, `kubewatch` is not really designed to be a "cloud native" app, ironically :-)

**Comment by dudicoco** [comment]
@mkmik O was also referring to the secrets resource, with the following configuration:

```
apiVersion: v1
kind: Secret
data:
  KW_SLACK_TOKEN: xxxx

```

And within the deployment:

```
      containers:
      - name: kubewatch
        image: "bitnami/kubewatch:0.0.4-debian-9-r269"
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: kubewatch-env
```
