### ISSUE TITLE
kubewatch fails on Ubuntu Server's microk8s

### ISSUE THREAD

**Issue by kyle-downey** [bitnami-labs/kubewatch#210]
After running "microk8s.kubectl apply" for this Pod definition:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: default
spec:
  containers:
  - name: kubewatch
    image: bitnami/kubewatch
    imagePullPolicy: Always
    volumeMounts:
    - name: config-volume
      mountPath: /opt/bitnami/kubewatch/.kubewatch.yaml
      subPath: .kubewatch.yaml
  - name: proxy
    image: bitnami/kubectl
    args:
      - proxy
      - "-p"
      - "8080"
    imagePullPolicy: Always
  restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch
```

with configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
data:
  .kubewatch.yaml: |
    namespace: ""
    handler:
      slack:
        token: "********"
        channel: "#kubernetes"
    resource:
      deployment: false
      replicationcontroller: false
      replicaset: false
      daemonset: false
      services: true
      pod: true
      secret: false
      configmap: false
```

it's up and running, but logging errors that seem to be related to accessing the local API:

ERROR: logging before flag.Parse: E0314 17:19:36.252188       1 reflector.go:205] github.com/bitnami-labs/kubewatch/pkg/controller/controller.go:377: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"94|..., bigger context ...|"f:version":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"94dce547-793e-44cd-b7e3-b35fd3019f86\"}":{|...
