### ISSUE TITLE
MS Teams handler not working in Helm chart

### ISSUE THREAD

**Issue by jonbesga** [bitnami-labs/kubewatch#214]
Hi, I'm currently using the version 1.0.13 of the bitnami/kubewatch chart. I know the chart doesn't support MS Teams in the values yet so I edited the config map once the helm release was installed.

My config map looks like this:

```
apiVersion: v1
data:
  .kubewatch.yaml: |
    handler:
      msteams:
        webhookurl: <REDACTED>
    resource:
      daemonset: false
      deployment: true
      job: false
      persistentvolume: false
      pod: false
      replicaset: false
      replicationcontroller: false
      services: false
kind: ConfigMap
```

Using the handler described above doesn't work. However, if I replace it for a normal webhook it sends a message to the Teams channel successfully.

```
    handler:
          webhook:
              url: <REDACTED>
```

Is the msteams handler actually working? The chart is using the version 0.0.4 of kubewatch, and 0.0.4 included the commits related to the msteams handler.
