### ISSUE TITLE
cannot list resource on Google Kubenestes Engine

### ISSUE THREAD

**Issue by jackkwok** [bitnami-labs/kubewatch#243]
`github.com/bitnami-labs/kubewatch/pkg/controller/controller.go:466: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:default:kubewatch" cannot list resource "namespaces" in API group "" at the cluster scope`

I followed the Kubectl RBAC instructions step by step but still received the above error.  Please help.

**Comment by gennway** [comment]
have you found the solution?

**Comment by cthulhu666** [comment]
@jackkwok you have to edit yaml file that contains `ClusterRole`
```
rules:
  - apiGroups: [""]
    resources: ["pods", "replicationcontrollers", "namespaces", "deployments", "services"] # <--- add resources here
    verbs: ["get", "watch", "list"]
```
