### ISSUE TITLE
helm install kubewatch with values.yaml , configmap still use slack webhook(did not use it)

### ISSUE THREAD

**Issue by 54853315** [bitnami-labs/kubewatch#255]
Hi everyone, I encountered a very strange problem.

I use helm chart (0.1.0) to update and deploy :

`helm upgrade --install --create-namespace -n kube-watch -f values.yaml kubewatch bitnami/kubewatch`

This is my configuration part: 

```
slack:
  enabled: false
  # Slack channel to notify
  channel: "XXXX"
  # Slack bots token. Create using: https://my.slack.com/services/new/bot
  # and invite the bot to your channel using: /join @botname
  token: "XXXX"

hipchat:
  enabled: false
  # room: ""
  # token: ""
  # url: ""
mattermost:
  enabled: false
  # channel: ""
  # url: ""
  # username: ""
flock:
  enabled: false
  # url: ""
msteams:
  enabled: false
  # webhookurl: ""
webhook:
  enabled: true
  url: "http://wechat-webhook:8080"
smtp:
  enabled: false
```

And logs keep reporting (`invalid_auth`): 
```
time="2021-01-11T09:43:08Z" level=info msg="Processing update to pod: *****-com-staging/backend-67fbf8d7dd-ntbm9" pkg=kubewatch-pod
2021/01/11 09:43:09 invalid_auth
```

Then check the configmap, what you get is:

```
Data
====
.kubewatch.yaml:
----
handler:
  slack:
    channel: XXXX
    enabled: true
    token: XXXX
resource:
  daemonset: false
  deployment: true
  job: false
  persistentvolume: false
  pod: true
  replicaset: false
  replicationcontroller: false
  services: false
namespace: ""

Events:  <none>
```
