### ISSUE TITLE
namespace missed in slack text message?

### ISSUE THREAD

**Issue by dmitry-mightydevops** [bitnami-labs/kubewatch#267]
![image](https://user-images.githubusercontent.com/70822710/117555834-675fcc80-b017-11eb-925c-2273da72120a.png)

HELM Chart version:

```
repoURL: https://charts.bitnami.com/bitnami
targetRevision: 3.2.4
```

**values**:
```
slack:
  enabled: true
  channel: "alarms"
  token: "xoxb-...."

webhook:
  enabled: false
  # url: ""
smtp:
  enabled: false

# namespace to watch, leave it empty for watching all.
namespaceToWatch: ""

# Resources to watch
resourcesToWatch:
  deployment: true
  replicationcontroller: false
  replicaset: false
  daemonset: false
  services: true
  pod: true
  job: true
  persistentvolume: true
  ingress: true
  secrets: true
  nodes: true

replicaCount: 1

resources:
  limits: 
    cpu: 200m
    memory: 256Mi
  requests: 
    cpu: 200m
    memory: 10Mi

livenessProbe:
  enabled: false
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  enabled: false
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

nodeSelector: 
  ops: "true"

podLabels: {}
podAnnotations: {}

rbac:
  create: true

serviceAccount:
  create: true
  name: "kubewatch-sa"
```
