### ISSUE TITLE
Ignoring certain messages

### ISSUE THREAD

**Issue by withernet** [bitnami-labs/kubewatch#273]
Lets say I only care about when a node is deleted or created, how do I prevent `kubewatch` from constantly flooding with `updated` messages?

**Comment by Ashtonian** [comment]
similar use case - we are on eks and they recycle the kube proxy (provided by aws plugin) at least once an hour.

**Comment by tonholis** [comment]
+1

**Comment by m0sh1x2** [comment]
I am using ```docker.io/bitnami/kubewatch:0.1.0-debian-10-r429"``` and it is constantly flooding with update messages.

**Comment by aantn** [comment]
If this is still relevant for anyone, I wrote an open source project on top of Kubewatch (see [here](https://docs.robusta.dev/master/)) which lets you apply filters in yaml. E.g. you can write:

```yaml
triggers:
- on_node_update: {}
actions:
- resource_babysitter:
     fields_to_monitor: ["spec"]
     omitted_fields: [
        "status",
        "metadata.generation",
        "metadata.resourceVersion",
        "metadata.managedFields",
     ]
```

Happy to add features if anyone needs.
